import { PrismaClient } from "@prisma/client";

// The Prisma client is generated by `apps/chg-rehab` (single shared schema,
// single DATABASE_URL). npm workspaces hoist the dependency so this import
// resolves to the same generated client chg-rehab uses.
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === "development" ? ["error", "warn"] : ["error"],
  });

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
